Tests and allure report
KseniyaRyabova/Sprint_3-2 pull request #1
Opened 2022-06-26 15:13 UTC by KseniyaRyabova

2022-06-28 06:27 UTC, nrasskosova requested changes

2022-06-28 06:27 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +                .post(String.format("%s/api/v1/courier", URL))
А знаешь почему не сработал setUp из родительского класса?
Потому что в родительском классе используется @Before аннотация - этот метод вызывается перед методом. А в этом классе ты используешь аннотацию @BeforeClass и она вызывается раньше, чем метод из родительского класса. 
Я думаю, что аннотации @BeforeClass достаточно в базовом классе.

2022-06-28 06:27 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +                .header("Content-type", "application/json")
настройка хедеров в каждом тесте. Это настройку также можно вынести в базовый класс

2022-06-28 06:27 UTC, nrasskosova commented on src/main/java/OrderRequest.java
> +    public OrderRequest(String firstName, String lastName, String address, int metroStation,
этот конструктор отличается от предыдущего только один параметром.

Можно вызывать конструктор с параметром null вместо color:

this( парамтеры...);

2022-06-28 06:27 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +public class CreateCourierTest extends BaseTest {
не вижу тестов:

если одного из полей нет, запрос возвращает ошибку;
если создать пользователя с логином, который уже есть, возвращается ошибка.

2022-06-28 06:27 UTC, nrasskosova commented on src/test/java/LoginCourierTest.java
> +                .body(new Courier("ksyusha", "12345"))
вот тут происходит логин под пользователем, но я не вижу методов, которые создают этого курьера и затем удаляют.

Нужно подчищать за собой данные

2022-06-28 06:27 UTC, nrasskosova commented on src/test/java/CreateOrderTest.java
> +                {new OrderRequest("firstName", "Naruto", "Konoha, 142 apt.",
Часть данных повторяется, меняется только цвет.

Лучше вынести общие параметры и задавать в параметрах только цвета

2022-06-28 20:03 UTC, KseniyaRyabova commented on src/test/java/LoginCourierTest.java
> +                .body(new Courier("ksyusha", "12345"))
Эти методы в классе "CreateCourierTest"

2022-06-29 12:18 UTC, nrasskosova requested changes

2022-06-29 12:18 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +    public static void deleteCourier() {
1. @Before и @After методы лучше располагать в начале тестового класса, чтоб было видно, что они есть
2. этот after метод перегружен. Для этого класса оптимальным будет делать не @AfterClass метод, а @After, который будет удалять созданного пользователя после каждого теста.

2022-06-29 12:18 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +        Courier courier2 = new Courier(loginForClassConfig2, passwordForClassConfig);
а если таких курьеров будет 10?

2022-06-30 16:18 UTC, KseniyaRyabova commented on src/test/java/CreateCourierTest.java
> +        Courier courier2 = new Courier(loginForClassConfig2, passwordForClassConfig);
Да уж, это было на редкость глупое решение, исправлено

2022-06-30 16:32 UTC, KseniyaRyabova commented on src/test/java/CreateCourierTest.java
> +    public static void deleteCourier() {
@nrasskosova, в данном случае я не могу сделать аннотацию @after, тк есть тест на создание уже существующего пользователя. Он падает, если в переделаю аннотацию в @After.
Можно, конечно, разделить удаление тестовых данных на @After и @AfterClass, но, мне кажется в этом нет необходимости вроде бы. 
В данном случае только один тестовый кейс подразумевает создание пользователя, остальные создавать пользователей не должны. 
Но непонятно, что делать, если валидации НЕ отработала и пользователь создался - нужно ли чистить данные в таком случае? И как это сделать, если вероятно пользователь может и не создаться и постусловие на удаление упадет?

2022-07-01 12:57 UTC, nrasskosova commented on src/test/java/CreateCourierTest.java
> +    public static void deleteCourier() {
падает, потому что курьер создается в    @BeforeClass, а после первого теста он удалится в @After методе и второй тест уже будет падать.
Для этого теста можно оставить как есть.
Если валидация не сработала, то самое простое - это добавить условие if, и внутри вызывать метод удаления созданного круьера

2022-07-07 16:03 UTC, merged